/** @deprecated 请从 @g-motion/webgpu 导入 WebGPUConstants */
export const WebGPUConstants = {
  WORKGROUP: {
    SIZE_DEFAULT: 128,
    SIZE_SMALL: 32,
    SIZE_MEDIUM: 64,
    SIZE_LARGE: 128,
    SIZE_XLARGE: 256,
    ENTITY_COUNT_XLARGE_THRESHOLD: 512,
    ENTITY_COUNT_SMALL_THRESHOLD: 32,
    ENTITY_COUNT_MEDIUM_THRESHOLD: 128,
  },

  BUFFER: {
    ALIGNMENT: 256,
    STRIDE_KEYFRAME: 10,
    STRIDE_SPRING_STATE: 8,
    STRIDE_INERTIA_STATE: 8,
    STRIDE_PHYSICS_STATE: 16,
    STRIDE_SIM_PARAMS_FLOATS: 4,
  },

  GPU: {
    TAIL_KEEP_ALIVE_MS: 250,
    DEFAULT_READBACK_TIMEOUT_MS: 100,
    MAX_READBACK_TIMEOUT_MS: 200,
    PHYSICS_MAX_VELOCITY_DEFAULT: 10000,
    PHYSICS_SETTLE_THRESHOLD_DEFAULT: 0.001,
  },
} as const;
