/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as WebgpuRouteImport } from './routes/webgpu';
import { Route as ObjectRouteImport } from './routes/object';
import { Route as FireworksRouteImport } from './routes/fireworks';
import { Route as DomRouteImport } from './routes/dom';
import { Route as IndexRouteImport } from './routes/index';

const WebgpuRoute = WebgpuRouteImport.update({
  id: '/webgpu',
  path: '/webgpu',
  getParentRoute: () => rootRouteImport,
} as any);
const ObjectRoute = ObjectRouteImport.update({
  id: '/object',
  path: '/object',
  getParentRoute: () => rootRouteImport,
} as any);
const FireworksRoute = FireworksRouteImport.update({
  id: '/fireworks',
  path: '/fireworks',
  getParentRoute: () => rootRouteImport,
} as any);
const DomRoute = DomRouteImport.update({
  id: '/dom',
  path: '/dom',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/dom': typeof DomRoute;
  '/fireworks': typeof FireworksRoute;
  '/object': typeof ObjectRoute;
  '/webgpu': typeof WebgpuRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/dom': typeof DomRoute;
  '/fireworks': typeof FireworksRoute;
  '/object': typeof ObjectRoute;
  '/webgpu': typeof WebgpuRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/dom': typeof DomRoute;
  '/fireworks': typeof FireworksRoute;
  '/object': typeof ObjectRoute;
  '/webgpu': typeof WebgpuRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/dom' | '/fireworks' | '/object' | '/webgpu';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/dom' | '/fireworks' | '/object' | '/webgpu';
  id: '__root__' | '/' | '/dom' | '/fireworks' | '/object' | '/webgpu';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DomRoute: typeof DomRoute;
  FireworksRoute: typeof FireworksRoute;
  ObjectRoute: typeof ObjectRoute;
  WebgpuRoute: typeof WebgpuRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webgpu': {
      id: '/webgpu';
      path: '/webgpu';
      fullPath: '/webgpu';
      preLoaderRoute: typeof WebgpuRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/object': {
      id: '/object';
      path: '/object';
      fullPath: '/object';
      preLoaderRoute: typeof ObjectRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/fireworks': {
      id: '/fireworks';
      path: '/fireworks';
      fullPath: '/fireworks';
      preLoaderRoute: typeof FireworksRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/dom': {
      id: '/dom';
      path: '/dom';
      fullPath: '/dom';
      preLoaderRoute: typeof DomRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DomRoute: DomRoute,
  FireworksRoute: FireworksRoute,
  ObjectRoute: ObjectRoute,
  WebgpuRoute: WebgpuRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
