/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as WebgpuRouteImport } from './routes/webgpu';
import { Route as SpringRouteImport } from './routes/spring';
import { Route as ParticlesFpsRouteImport } from './routes/particles-fps';
import { Route as ObjectRouteImport } from './routes/object';
import { Route as GpuDeliveryDemoRouteImport } from './routes/gpu-delivery-demo';
import { Route as GpuConfigRouteImport } from './routes/gpu-config';
import { Route as EngineConfigRouteImport } from './routes/engine-config';
import { Route as Dom3dRouteImport } from './routes/dom-3d';
import { Route as DomRouteImport } from './routes/dom';
import { Route as CustomEasingRouteImport } from './routes/custom-easing';
import { Route as IndexRouteImport } from './routes/index';

const WebgpuRoute = WebgpuRouteImport.update({
  id: '/webgpu',
  path: '/webgpu',
  getParentRoute: () => rootRouteImport,
} as any);
const SpringRoute = SpringRouteImport.update({
  id: '/spring',
  path: '/spring',
  getParentRoute: () => rootRouteImport,
} as any);
const ParticlesFpsRoute = ParticlesFpsRouteImport.update({
  id: '/particles-fps',
  path: '/particles-fps',
  getParentRoute: () => rootRouteImport,
} as any);
const ObjectRoute = ObjectRouteImport.update({
  id: '/object',
  path: '/object',
  getParentRoute: () => rootRouteImport,
} as any);
const GpuDeliveryDemoRoute = GpuDeliveryDemoRouteImport.update({
  id: '/gpu-delivery-demo',
  path: '/gpu-delivery-demo',
  getParentRoute: () => rootRouteImport,
} as any);
const GpuConfigRoute = GpuConfigRouteImport.update({
  id: '/gpu-config',
  path: '/gpu-config',
  getParentRoute: () => rootRouteImport,
} as any);
const EngineConfigRoute = EngineConfigRouteImport.update({
  id: '/engine-config',
  path: '/engine-config',
  getParentRoute: () => rootRouteImport,
} as any);
const Dom3dRoute = Dom3dRouteImport.update({
  id: '/dom-3d',
  path: '/dom-3d',
  getParentRoute: () => rootRouteImport,
} as any);
const DomRoute = DomRouteImport.update({
  id: '/dom',
  path: '/dom',
  getParentRoute: () => rootRouteImport,
} as any);
const CustomEasingRoute = CustomEasingRouteImport.update({
  id: '/custom-easing',
  path: '/custom-easing',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/custom-easing': typeof CustomEasingRoute;
  '/dom': typeof DomRoute;
  '/dom-3d': typeof Dom3dRoute;
  '/engine-config': typeof EngineConfigRoute;
  '/gpu-config': typeof GpuConfigRoute;
  '/gpu-delivery-demo': typeof GpuDeliveryDemoRoute;
  '/object': typeof ObjectRoute;
  '/particles-fps': typeof ParticlesFpsRoute;
  '/spring': typeof SpringRoute;
  '/webgpu': typeof WebgpuRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/custom-easing': typeof CustomEasingRoute;
  '/dom': typeof DomRoute;
  '/dom-3d': typeof Dom3dRoute;
  '/engine-config': typeof EngineConfigRoute;
  '/gpu-config': typeof GpuConfigRoute;
  '/gpu-delivery-demo': typeof GpuDeliveryDemoRoute;
  '/object': typeof ObjectRoute;
  '/particles-fps': typeof ParticlesFpsRoute;
  '/spring': typeof SpringRoute;
  '/webgpu': typeof WebgpuRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/custom-easing': typeof CustomEasingRoute;
  '/dom': typeof DomRoute;
  '/dom-3d': typeof Dom3dRoute;
  '/engine-config': typeof EngineConfigRoute;
  '/gpu-config': typeof GpuConfigRoute;
  '/gpu-delivery-demo': typeof GpuDeliveryDemoRoute;
  '/object': typeof ObjectRoute;
  '/particles-fps': typeof ParticlesFpsRoute;
  '/spring': typeof SpringRoute;
  '/webgpu': typeof WebgpuRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/custom-easing'
    | '/dom'
    | '/dom-3d'
    | '/engine-config'
    | '/gpu-config'
    | '/gpu-delivery-demo'
    | '/object'
    | '/particles-fps'
    | '/spring'
    | '/webgpu';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/custom-easing'
    | '/dom'
    | '/dom-3d'
    | '/engine-config'
    | '/gpu-config'
    | '/gpu-delivery-demo'
    | '/object'
    | '/particles-fps'
    | '/spring'
    | '/webgpu';
  id:
    | '__root__'
    | '/'
    | '/custom-easing'
    | '/dom'
    | '/dom-3d'
    | '/engine-config'
    | '/gpu-config'
    | '/gpu-delivery-demo'
    | '/object'
    | '/particles-fps'
    | '/spring'
    | '/webgpu';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CustomEasingRoute: typeof CustomEasingRoute;
  DomRoute: typeof DomRoute;
  Dom3dRoute: typeof Dom3dRoute;
  EngineConfigRoute: typeof EngineConfigRoute;
  GpuConfigRoute: typeof GpuConfigRoute;
  GpuDeliveryDemoRoute: typeof GpuDeliveryDemoRoute;
  ObjectRoute: typeof ObjectRoute;
  ParticlesFpsRoute: typeof ParticlesFpsRoute;
  SpringRoute: typeof SpringRoute;
  WebgpuRoute: typeof WebgpuRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webgpu': {
      id: '/webgpu';
      path: '/webgpu';
      fullPath: '/webgpu';
      preLoaderRoute: typeof WebgpuRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/spring': {
      id: '/spring';
      path: '/spring';
      fullPath: '/spring';
      preLoaderRoute: typeof SpringRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/particles-fps': {
      id: '/particles-fps';
      path: '/particles-fps';
      fullPath: '/particles-fps';
      preLoaderRoute: typeof ParticlesFpsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/object': {
      id: '/object';
      path: '/object';
      fullPath: '/object';
      preLoaderRoute: typeof ObjectRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/gpu-delivery-demo': {
      id: '/gpu-delivery-demo';
      path: '/gpu-delivery-demo';
      fullPath: '/gpu-delivery-demo';
      preLoaderRoute: typeof GpuDeliveryDemoRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/gpu-config': {
      id: '/gpu-config';
      path: '/gpu-config';
      fullPath: '/gpu-config';
      preLoaderRoute: typeof GpuConfigRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/engine-config': {
      id: '/engine-config';
      path: '/engine-config';
      fullPath: '/engine-config';
      preLoaderRoute: typeof EngineConfigRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/dom-3d': {
      id: '/dom-3d';
      path: '/dom-3d';
      fullPath: '/dom-3d';
      preLoaderRoute: typeof Dom3dRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/dom': {
      id: '/dom';
      path: '/dom';
      fullPath: '/dom';
      preLoaderRoute: typeof DomRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/custom-easing': {
      id: '/custom-easing';
      path: '/custom-easing';
      fullPath: '/custom-easing';
      preLoaderRoute: typeof CustomEasingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomEasingRoute: CustomEasingRoute,
  DomRoute: DomRoute,
  Dom3dRoute: Dom3dRoute,
  EngineConfigRoute: EngineConfigRoute,
  GpuConfigRoute: GpuConfigRoute,
  GpuDeliveryDemoRoute: GpuDeliveryDemoRoute,
  ObjectRoute: ObjectRoute,
  ParticlesFpsRoute: ParticlesFpsRoute,
  SpringRoute: SpringRoute,
  WebgpuRoute: WebgpuRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
