import { GPU_DEFAULTS } from '@g-motion/shared';

export const WebGPUConstants = {
  WORKGROUP: GPU_DEFAULTS.WORKGROUP,

  BUFFER: {
    ALIGNMENT: 256,
    STRIDE_KEYFRAME: 10,
    STRIDE_SPRING_STATE: 8,
    STRIDE_INERTIA_STATE: 8,
    STRIDE_PHYSICS_STATE: 16,
    STRIDE_SIM_PARAMS_FLOATS: 4,
  },

  GPU: {
    ...GPU_DEFAULTS.GPU,
    DEFAULT_READBACK_TIMEOUT_MS: 100,
    MAX_READBACK_TIMEOUT_MS: 200,
  },
} as const;
